# Import lib

In [1]:
import open3d as o3d
import numpy as np

In [2]:
!pwd

/Users/zili/condaProjects/open3D


## Cloud Points

In [3]:
pcd = o3d.io.read_point_cloud("./data/California office chair.ply")
print(pcd)

# write file
# o3d.io.write_point_cloud("./data/copy California office chair.ply", pcd)

geometry::PointCloud with 250002 points.


## Mesh

In [4]:
mesh = o3d.io.read_triangle_mesh("./data/California office chair.ply")
print(mesh)
# o3d.io.write_triangle_mesh("./data/copy2 California office chair.ply", mesh)

geometry::TriangleMesh with 250002 points and 500000 triangles.


## Visualize point cloud

In [5]:
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

[[-239.12382507    5.45855808  248.66607666]
 [ 342.00787354  358.88113403 -173.93942261]
 [ -69.06135559 -220.93701172  253.87741089]
 ...
 [ 335.16723633  194.0070343  -168.71589661]
 [ 375.25610352  341.95254517  -22.58455658]
 [  47.64028549 -453.11102295  405.27212524]]


## Voxel downsampling & Vertex normal estimation

In [6]:
downpcd = pcd.voxel_down_sample(voxel_size=0.005)
o3d.visualization.draw_geometries([downpcd])

In [7]:
downpcd.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
o3d.visualization.draw_geometries([downpcd], 
                                  point_show_normal=True)

In [8]:
print("Print a normal vector of the 0th point")
print(downpcd.normals[0])

Print a normal vector of the 0th point
[0. 0. 1.]


## Draw line set

In [9]:
aabb = pcd.get_axis_aligned_bounding_box()
aabb.color = (1,0,0)
obb = pcd.get_oriented_bounding_box()
obb.color = (0,1,0)
o3d.visualization.draw_geometries([pcd, aabb, obb])

In [14]:
points = [
        [0, 0, 0],
        [0, 0, 500],
        [500, 0, 0],
        [0, 500, 0]
]
lines = [
        [0, 1],
        [0, 2],
        [0, 3]
]
colors = [[1, 0, 0] for i in range(len(lines))]
line_set = o3d.geometry.LineSet(
    points=o3d.utility.Vector3dVector(points),
    lines=o3d.utility.Vector2iVector(lines),
)
line_set.colors = o3d.utility.Vector3dVector(colors)
o3d.visualization.draw_geometries([pcd, line_set])