In [5]:
import open3d as o3d
import numpy as np

## target femur model(stl. mesh)

#### read target file

In [6]:
femur_mesh = o3d.io.read_triangle_mesh("./data/Femur.stl")

#### visualization mesh

In [7]:
o3d.visualization.draw_geometries([femur_mesh])

#### sample to point clould

In [8]:
femur_pcd = femur_mesh.sample_points_poisson_disk(number_of_points=100000)

#### visulazation point clould

In [9]:
o3d.visualization.draw_geometries([femur_pcd])

sava output pcd file 

In [10]:
o3d.io.write_point_cloud("./data/copy_femur.ply", femur_pcd)

True

read modified file

In [11]:
pcd = o3d.io.read_point_cloud("./data/copy_femur.ply")

In [12]:
o3d.visualization.draw_geometries([pcd])

In [13]:
print(pcd)
print(np.asarray(pcd.points))

geometry::PointCloud with 100000 points.
[[-59.83874768  51.24883471 310.41121664]
 [-59.02417906  52.54168264 310.25412994]
 [-59.22436385  51.85390587 310.26536375]
 ...
 [113.54694479  14.76333199 694.82315097]
 [114.26500347  12.44172887 694.92050143]
 [114.41660599  13.08072376 694.90189666]]


In [14]:
mesh = o3d.io.read_triangle_mesh("./data/copy_femur.ply")

[Open3D WARNING] geometry::TriangleMesh appears to be a geometry::PointCloud (only contains vertices, but no triangles).


In [19]:
box = o3d.geometry.OrientedBoundingBox.get_box_points(pcd)

TypeError: get_box_points(): incompatible function arguments. The following argument types are supported:
    1. (self: open3d.open3d_pybind.geometry.OrientedBoundingBox) -> open3d.open3d_pybind.utility.Vector3dVector

Invoked with: geometry::PointCloud with 100000 points.